name: TeleportPlugin
main: de.schrottwald.gateplugin.TeleportPlugin
version: 0.1
commands:
   setPort:
      description: This sets a port point.
      usage: /<command>
      permission: TeleportPlugin.basic
      permission-message: You don't have <permission>

   port:
     description: This sets a port point.
     usage: /<command>
     permission: TeleportPlugin.basic
     permission-message: You don't have <permission>


