name: TeleportPlugin
main: de.schrottwald.TeleportPlugin
version: 0.1
commands:
   test:
      description: This is a demo command.
      usage: /<command> [player]
      permission: TeleportPlugin.basic
      permission-message: You don't have <permission>

   ping:

